Add validation step to version.yml
Recent run attepts revealed that the action eats up error messages from
npm version and silently fails, while outwardly claiming to succeed.

This commit seeks to somewhat remedy that by validating the output from
npm version to ensure it ran as expected.

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -52,5 +52,13 @@ jobs:
         git config --global user.email "${{ github.actor }}@users.noreply.github.com"
     - name: npm version ${{ inputs.version }}
       run: echo "version=$(npm version ${{ inputs.version }}${{ startsWith(inputs.version, 'pre') && ' --preid beta' || '' }})" >> "$GITHUB_ENV"
+    - name: Validate npm version
+      run: : |
+        # the above step silently fails, so validate the output was set
+        if [[ -z ${{ env.version }} ]]; then
+          exit 1;
+        else
+          echo ${{ env.version }}
+        fi
     - name: git push
       run: git push && git push origin ${{ env.version }}
